### ISSUE TITLE
Can this run on NVIDIA-GPU?

### ISSUE THREAD

**Issue by 2catycm** [huggingface/bloom-jax-inference#8]
As I know, Jax is designed for GOOGLE-TPU, but it can also run on NVIDIA-GPU.
I wonder if jax may be faster or slower than pytorch on GPU for bloom llm inference.

**Comment by Narsil** [comment]
Try and tell us ? 

Performance depends on soooo many factors.

This repo is not used anymore, we use : https://github.com/huggingface/text-generation-inference pretty myuch for all our deployments.
